spring:
    application:
      name: bem-me-quer
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${MYSQL_URL}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}

