spring:
    jpa:
      hibernate:
        dll-auto: none
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${MYSQL_URL}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      initialization-mode: always



