spring:
    jpa:
      hibernate:
        dll-auto: none
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${MYSQL_URL}
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      initialization-mode: always
server:
  port: 9000


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health , prometheus"
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
